name: Self-Healing Pipeline

on:
  repository_dispatch:
    types: [retrain_model_event]
  workflow_dispatch:

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Ingest Data
        run: python src/data_ingestion.py

      # --- LOGIC SWITCH ---
      # If payload says 'simulate_drift: true', we add the flag.
      # If not, we run normally.
      - name: Retrain Model
        run: |
          if [ "${{ github.event.client_payload.simulate_drift }}" == "true" ]; then
            echo "üî• DRIFT REQUESTED!"
            python src/train.py --simulate-drift
          else
            echo "‚ùÑÔ∏è NORMAL RESET REQUESTED."
            python src/train.py
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ridepulse-repo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Lambda
        run: |
          aws lambda update-function-code --function-name RidePulse-API --image-uri ${{ steps.login-ecr.outputs.registry }}/ridepulse-repo:latest