steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v3

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install Dependencies
        # Added pyarrow and fastparquet for the downloader
        run: |
          pip install pandas scikit-learn joblib xgboost requests scipy pyarrow fastparquet

      - name: 4. Ingest Data (Q1 2023)
        # This downloads the 1M rows directly to the cloud runner
        run: python src/data_ingestion.py

      - name: 5. Retrain Model
        run: python src/train.py

      - name: 6. Save Model as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: new-model-v2
          path: models/model_v1.joblib