name: Self-Healing Pipeline

on:
  # This listens for the signal from your laptop
  repository_dispatch:
    types: [retrain_model_event]
  
  # This allows you to click a "Run" button on the website manually to test it
  workflow_dispatch:

jobs:
  retrain_model:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v3

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install Dependencies
        # We install exactly what your script needs
        run: |
          pip install pandas scikit-learn joblib xgboost requests scipy

      - name: 4. Retrain Model
        # This runs the training script in the cloud
        run: python src/train.py

      - name: 5. Save Model as Artifact
        # This saves the model file so you can download it from the GitHub UI
        uses: actions/upload-artifact@v4
        with:
          name: new-model-v2
          path: models/model_v1.joblib